services:
  - type: web
    name: importador-xml-sankhya
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_SANDBOX
        value: "true"
      - key: SANKHYA_BASE_URL
        value: https://api.sankhya.com.br
      - key: SANKHYA_TOKEN
        sync: false
      - key: SANKHYA_APPKEY
        sync: false
      - key: SANKHYA_CODEMP
        value: "1"
      - key: SANKHYA_TOP
        value: "102"
      - key: SANKHYA_CODTIPVENDA
        value: "1"
      - key: SANKHYA_CODVEND
        value: "0"
